[package]

name = "bit"
version = "0.1.0"
edition = "2021"
publish = false

default-run = "bit"

[lib]
name = "bit"
path = "lib.rs"

[[bin]]
name = "bit"
path = "bit.rs"

[dependencies]

rand = "0.8.5"
